apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: cource
        value: kubernates
      - name: traainer
        value: bala
