apiVersion: 1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    project:  roboshop
    comoponent: froentend
    environment:  dev
    purpose:  load-balancer
  ports:
  - protocol: TCP
    port:  80
    targetPort: 80
    NodePort: 30007